package com.auto.di.guan.db.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.auto.di.guan.db.User;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER".
*/
public class UserDao extends AbstractDao<User, Long> {

    public static final String TABLENAME = "USER";

    /**
     * Properties of entity User.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, Long.class, "userId", false, "userId");
        public final static Property MemberId = new Property(2, Long.class, "memberId", false, "memberId");
        public final static Property DeptId = new Property(3, Long.class, "deptId", false, "deptId");
        public final static Property ParentId = new Property(4, Long.class, "parentId", false, "parentId");
        public final static Property RoleId = new Property(5, Long.class, "roleId", false, "roleId");
        public final static Property LoginName = new Property(6, String.class, "loginName", false, "loginName");
        public final static Property UserName = new Property(7, String.class, "userName", false, "userName");
        public final static Property UserType = new Property(8, String.class, "userType", false, "userType");
        public final static Property Email = new Property(9, String.class, "email", false, "email");
        public final static Property Phonenumber = new Property(10, String.class, "phonenumber", false, "phonenumber");
        public final static Property Sex = new Property(11, String.class, "sex", false, "sex");
        public final static Property Avatar = new Property(12, String.class, "avatar", false, "avatar");
        public final static Property Password = new Property(13, String.class, "password", false, "password");
        public final static Property Salt = new Property(14, String.class, "salt", false, "salt");
        public final static Property Status = new Property(15, String.class, "status", false, "status");
        public final static Property DelFlag = new Property(16, String.class, "delFlag", false, "delFlag");
        public final static Property LoginIp = new Property(17, String.class, "loginIp", false, "loginIp");
        public final static Property LoginDate = new Property(18, java.util.Date.class, "loginDate", false, "loginDate");
        public final static Property Mac = new Property(19, String.class, "mac", false, "mac");
        public final static Property ProjectId = new Property(20, String.class, "projectId", false, "projectId");
        public final static Property ProjectGroupId = new Property(21, String.class, "projectGroupId", false, "projectGroupId");
        public final static Property TrunkPipeNum = new Property(22, int.class, "trunkPipeNum", false, "trunkPipeNum");
        public final static Property TrunkPipeMaxNum = new Property(23, int.class, "trunkPipeMaxNum", false, "trunkPipeMaxNum");
        public final static Property PileOutNum = new Property(24, int.class, "pileOutNum", false, "pileOutNum");
        public final static Property ProjectName = new Property(25, String.class, "projectName", false, "projectName");
        public final static Property ProjectDesc = new Property(26, String.class, "projectDesc", false, "projectDesc");
        public final static Property ProjectRemarks = new Property(27, String.class, "projectRemarks", false, "projectRemarks");
        public final static Property LongitudeLatitude = new Property(28, String.class, "longitudeLatitude", false, "longitudeLatitude");
        public final static Property ParentLoginName = new Property(29, String.class, "parentLoginName", false, "parentLoginName");
    }


    public UserDao(DaoConfig config) {
        super(config);
    }
    
    public UserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"userId\" INTEGER," + // 1: userId
                "\"memberId\" INTEGER," + // 2: memberId
                "\"deptId\" INTEGER," + // 3: deptId
                "\"parentId\" INTEGER," + // 4: parentId
                "\"roleId\" INTEGER," + // 5: roleId
                "\"loginName\" TEXT," + // 6: loginName
                "\"userName\" TEXT," + // 7: userName
                "\"userType\" TEXT," + // 8: userType
                "\"email\" TEXT," + // 9: email
                "\"phonenumber\" TEXT," + // 10: phonenumber
                "\"sex\" TEXT," + // 11: sex
                "\"avatar\" TEXT," + // 12: avatar
                "\"password\" TEXT," + // 13: password
                "\"salt\" TEXT," + // 14: salt
                "\"status\" TEXT," + // 15: status
                "\"delFlag\" TEXT," + // 16: delFlag
                "\"loginIp\" TEXT," + // 17: loginIp
                "\"loginDate\" INTEGER," + // 18: loginDate
                "\"mac\" TEXT," + // 19: mac
                "\"projectId\" TEXT," + // 20: projectId
                "\"projectGroupId\" TEXT," + // 21: projectGroupId
                "\"trunkPipeNum\" INTEGER NOT NULL ," + // 22: trunkPipeNum
                "\"trunkPipeMaxNum\" INTEGER NOT NULL ," + // 23: trunkPipeMaxNum
                "\"pileOutNum\" INTEGER NOT NULL ," + // 24: pileOutNum
                "\"projectName\" TEXT," + // 25: projectName
                "\"projectDesc\" TEXT," + // 26: projectDesc
                "\"projectRemarks\" TEXT," + // 27: projectRemarks
                "\"longitudeLatitude\" TEXT," + // 28: longitudeLatitude
                "\"parentLoginName\" TEXT);"); // 29: parentLoginName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, User entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long userId = entity.getUserId();
        if (userId != null) {
            stmt.bindLong(2, userId);
        }
 
        Long memberId = entity.getMemberId();
        if (memberId != null) {
            stmt.bindLong(3, memberId);
        }
 
        Long deptId = entity.getDeptId();
        if (deptId != null) {
            stmt.bindLong(4, deptId);
        }
 
        Long parentId = entity.getParentId();
        if (parentId != null) {
            stmt.bindLong(5, parentId);
        }
 
        Long roleId = entity.getRoleId();
        if (roleId != null) {
            stmt.bindLong(6, roleId);
        }
 
        String loginName = entity.getLoginName();
        if (loginName != null) {
            stmt.bindString(7, loginName);
        }
 
        String userName = entity.getUserName();
        if (userName != null) {
            stmt.bindString(8, userName);
        }
 
        String userType = entity.getUserType();
        if (userType != null) {
            stmt.bindString(9, userType);
        }
 
        String email = entity.getEmail();
        if (email != null) {
            stmt.bindString(10, email);
        }
 
        String phonenumber = entity.getPhonenumber();
        if (phonenumber != null) {
            stmt.bindString(11, phonenumber);
        }
 
        String sex = entity.getSex();
        if (sex != null) {
            stmt.bindString(12, sex);
        }
 
        String avatar = entity.getAvatar();
        if (avatar != null) {
            stmt.bindString(13, avatar);
        }
 
        String password = entity.getPassword();
        if (password != null) {
            stmt.bindString(14, password);
        }
 
        String salt = entity.getSalt();
        if (salt != null) {
            stmt.bindString(15, salt);
        }
 
        String status = entity.getStatus();
        if (status != null) {
            stmt.bindString(16, status);
        }
 
        String delFlag = entity.getDelFlag();
        if (delFlag != null) {
            stmt.bindString(17, delFlag);
        }
 
        String loginIp = entity.getLoginIp();
        if (loginIp != null) {
            stmt.bindString(18, loginIp);
        }
 
        java.util.Date loginDate = entity.getLoginDate();
        if (loginDate != null) {
            stmt.bindLong(19, loginDate.getTime());
        }
 
        String mac = entity.getMac();
        if (mac != null) {
            stmt.bindString(20, mac);
        }
 
        String projectId = entity.getProjectId();
        if (projectId != null) {
            stmt.bindString(21, projectId);
        }
 
        String projectGroupId = entity.getProjectGroupId();
        if (projectGroupId != null) {
            stmt.bindString(22, projectGroupId);
        }
        stmt.bindLong(23, entity.getTrunkPipeNum());
        stmt.bindLong(24, entity.getTrunkPipeMaxNum());
        stmt.bindLong(25, entity.getPileOutNum());
 
        String projectName = entity.getProjectName();
        if (projectName != null) {
            stmt.bindString(26, projectName);
        }
 
        String projectDesc = entity.getProjectDesc();
        if (projectDesc != null) {
            stmt.bindString(27, projectDesc);
        }
 
        String projectRemarks = entity.getProjectRemarks();
        if (projectRemarks != null) {
            stmt.bindString(28, projectRemarks);
        }
 
        String longitudeLatitude = entity.getLongitudeLatitude();
        if (longitudeLatitude != null) {
            stmt.bindString(29, longitudeLatitude);
        }
 
        String parentLoginName = entity.getParentLoginName();
        if (parentLoginName != null) {
            stmt.bindString(30, parentLoginName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, User entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long userId = entity.getUserId();
        if (userId != null) {
            stmt.bindLong(2, userId);
        }
 
        Long memberId = entity.getMemberId();
        if (memberId != null) {
            stmt.bindLong(3, memberId);
        }
 
        Long deptId = entity.getDeptId();
        if (deptId != null) {
            stmt.bindLong(4, deptId);
        }
 
        Long parentId = entity.getParentId();
        if (parentId != null) {
            stmt.bindLong(5, parentId);
        }
 
        Long roleId = entity.getRoleId();
        if (roleId != null) {
            stmt.bindLong(6, roleId);
        }
 
        String loginName = entity.getLoginName();
        if (loginName != null) {
            stmt.bindString(7, loginName);
        }
 
        String userName = entity.getUserName();
        if (userName != null) {
            stmt.bindString(8, userName);
        }
 
        String userType = entity.getUserType();
        if (userType != null) {
            stmt.bindString(9, userType);
        }
 
        String email = entity.getEmail();
        if (email != null) {
            stmt.bindString(10, email);
        }
 
        String phonenumber = entity.getPhonenumber();
        if (phonenumber != null) {
            stmt.bindString(11, phonenumber);
        }
 
        String sex = entity.getSex();
        if (sex != null) {
            stmt.bindString(12, sex);
        }
 
        String avatar = entity.getAvatar();
        if (avatar != null) {
            stmt.bindString(13, avatar);
        }
 
        String password = entity.getPassword();
        if (password != null) {
            stmt.bindString(14, password);
        }
 
        String salt = entity.getSalt();
        if (salt != null) {
            stmt.bindString(15, salt);
        }
 
        String status = entity.getStatus();
        if (status != null) {
            stmt.bindString(16, status);
        }
 
        String delFlag = entity.getDelFlag();
        if (delFlag != null) {
            stmt.bindString(17, delFlag);
        }
 
        String loginIp = entity.getLoginIp();
        if (loginIp != null) {
            stmt.bindString(18, loginIp);
        }
 
        java.util.Date loginDate = entity.getLoginDate();
        if (loginDate != null) {
            stmt.bindLong(19, loginDate.getTime());
        }
 
        String mac = entity.getMac();
        if (mac != null) {
            stmt.bindString(20, mac);
        }
 
        String projectId = entity.getProjectId();
        if (projectId != null) {
            stmt.bindString(21, projectId);
        }
 
        String projectGroupId = entity.getProjectGroupId();
        if (projectGroupId != null) {
            stmt.bindString(22, projectGroupId);
        }
        stmt.bindLong(23, entity.getTrunkPipeNum());
        stmt.bindLong(24, entity.getTrunkPipeMaxNum());
        stmt.bindLong(25, entity.getPileOutNum());
 
        String projectName = entity.getProjectName();
        if (projectName != null) {
            stmt.bindString(26, projectName);
        }
 
        String projectDesc = entity.getProjectDesc();
        if (projectDesc != null) {
            stmt.bindString(27, projectDesc);
        }
 
        String projectRemarks = entity.getProjectRemarks();
        if (projectRemarks != null) {
            stmt.bindString(28, projectRemarks);
        }
 
        String longitudeLatitude = entity.getLongitudeLatitude();
        if (longitudeLatitude != null) {
            stmt.bindString(29, longitudeLatitude);
        }
 
        String parentLoginName = entity.getParentLoginName();
        if (parentLoginName != null) {
            stmt.bindString(30, parentLoginName);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public User readEntity(Cursor cursor, int offset) {
        User entity = new User( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // userId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // memberId
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // deptId
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // parentId
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5), // roleId
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // loginName
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // userName
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // userType
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // email
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // phonenumber
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // sex
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // avatar
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // password
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // salt
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // status
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // delFlag
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // loginIp
            cursor.isNull(offset + 18) ? null : new java.util.Date(cursor.getLong(offset + 18)), // loginDate
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // mac
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // projectId
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // projectGroupId
            cursor.getInt(offset + 22), // trunkPipeNum
            cursor.getInt(offset + 23), // trunkPipeMaxNum
            cursor.getInt(offset + 24), // pileOutNum
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // projectName
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // projectDesc
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // projectRemarks
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // longitudeLatitude
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29) // parentLoginName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, User entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setMemberId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setDeptId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setParentId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setRoleId(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setLoginName(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setUserName(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setUserType(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setEmail(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setPhonenumber(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setSex(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setAvatar(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setPassword(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setSalt(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setStatus(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setDelFlag(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setLoginIp(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setLoginDate(cursor.isNull(offset + 18) ? null : new java.util.Date(cursor.getLong(offset + 18)));
        entity.setMac(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setProjectId(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setProjectGroupId(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setTrunkPipeNum(cursor.getInt(offset + 22));
        entity.setTrunkPipeMaxNum(cursor.getInt(offset + 23));
        entity.setPileOutNum(cursor.getInt(offset + 24));
        entity.setProjectName(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setProjectDesc(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setProjectRemarks(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setLongitudeLatitude(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setParentLoginName(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(User entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(User entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(User entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
